// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package internal

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TaskT struct {
	ID             int32
	Type           int16
	Value          int16
	State          string
	CreationTime   pgtype.Timestamp
	LastUpdateTime pgtype.Timestamp
}
